package msg

const (
	IdEmpty                 = "id为空"
	IdNotExist              = "id不存在"
	UsernameEmpty           = "用户名为空"
	UsernameAlreadyExist    = "用户名已存在"
	UsernameNotExist        = "用户名不存在"
	UsernameOrPasswordError = "用户名或密码错误"
	PasswordNotMatch        = "密码不匹配"
	UserAlreadyExist        = "用户已存在"
	UserNotExist            = "用户不存在"
	UserNotLogin            = "用户未登录"
	UserStateUnable         = "用户状态不可用"
	UserRoleUnable          = "用户角色不可用"
	UserPrivilegeUnable     = "用户权限不可用"
	UniqueAlreadyExist      = "唯一键已存在"
	UniqueNotExist          = "唯一键不存在"
	ObjectAlreadyExist      = "对象已存在"
	ObjectNotExist          = "对象不存在"
	ObjectEmpty             = "对象为空"
	EntityAlreadyExist      = "实体已存在"
	EntityNotExist          = "实体不存在"
	EntityEmpty             = "实体为空"
	DataAlreadyExist        = "数据已存在"
	DataNotExist            = "数据不存在"
	DataEmpty               = "数据为空"
	ParamEmpty              = "参数为空"
	ParamError              = "参数错误"
	ParamMissing            = "参数缺失"
	InterfaceError          = "接口错误"
	InterfaceTimeout        = "接口超时"
	RequestError            = "请求错误"
	RequestTimeout          = "请求超时"
	ServiceError            = "服务错误"
	ServiceTimeout          = "服务超时"
)
